
name: Sync Templates from Org Template Repo

on:
  schedule:
    - cron: "15 6 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    # Correct reference and use a valid ref (main or a tag)
    uses: winccoa-tools-pack/.github/.github/workflows/template-sync-reusable.yml@main
    with:
      template_repo: "winccoa-tools-pack/template-npm-shared-library"
      template_ref:  "main"
      sync_mode:     "update"
      paths: |
        .github/ISSUE_TEMPLATE/**/*.yml
# add more paths as needed
#        .github/ISSUE_TEMPLATE/**/*.yaml
      pr_title:  "chore(template): sync issue templates"
      pr_body:   "Automated sync from org template repository."
      pr_labels: "chore"
   #   pr_reviewers: "REPLACE_WITH_REAL_USERS_OR_TEAMS"
      branch_prefix: "chore/template-sync"
    secrets: inherit
